# Generated by Django 3.0.4 on 2020-04-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pens', '0002_ink'),
    ]

    operations = [
        migrations.AddField(
            model_name='ink',
            name='rating',
            field=models.IntegerField(default=None),
        ),
    ]
