# Generated by Django 3.0.4 on 2020-04-25 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pens', '0003_ink_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='pen',
            name='current_ink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pens.Ink'),
        ),
    ]
