# Generated by Django 3.0.5 on 2020-04-29 13:55

from django.db import migrations, models
import django.db.models.deletion
import pens.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('pens', '0004_pen_current_ink'),
    ]

    operations = [
        migrations.AddField(
            model_name='pen',
            name='added_by',
            field=models.ForeignKey(default=pens.models.get_default_user, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.Profile'),
        ),
    ]
